<?php

namespace App\Http\Controllers;

use App\Models\Competence;
use Illuminate\Http\Request;

class CompetenceController extends Controller
{
    public function show()
    {
        return(Competence::all()); // TODO: Change the autogenerated stub
    }
}
