<?php

namespace App\Http\Controllers;

use App\Models\Depocv;
use Illuminate\Http\Request;

class DepocvController extends Controller
{
    public function show()
    {
        return(Depocv::all()); // TODO: Change the autogenerated stub
    }
}
