<?php

namespace App\Http\Controllers;

use App\Models\FormationAcademique;
use Illuminate\Http\Request;

class FormationAcademiqueController extends Controller
{
    public function show()
    {
        return(FormationAcademique::all()); // TODO: Change the autogenerated stub
    }
}
